# Generated by Django 5.2.4 on 2025-07-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view'), ('can_create', 'can create'), ('can_edit', 'can edit'), ('can_delete', 'can delete')]},
        ),
    ]
